kind: Namespace
apiVersion: v1
metadata:
  name: testing

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web-app
      labels:
        app: web
    spec:
      containers:
      - name: springapp
        image: invinsible007/web-app:1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---

kind: Service
apiVersion: v1
metadata:
  name: websvc
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080



